[package]
name = "example_ws_server_fetch_asset"
edition = "2021"
publish = false

[dependencies]
foxglove = { path = "../../foxglove" }
tokio = { version = "1.43", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11.5"
